### PR TITLE
Make tests pass, fix version conflict hell

### PR DESCRIPTION
**Pull request by connorshea**
Loosen some dependencies to get things working, fix up the test suite.
- Drop support for JRuby.

### CODE REVIEW

**Comment by connorshea** [comment]
Ugh, okay technically JRuby builds do pass on Rails 4.2, but they take 4x longer than all other tests :/

**Comment by connorshea** [comment]
@tubbo it's passing now 👍

**Comment by connorshea** [comment]
Okay, this no longer drops support for older versions of Rails or Ruby, it only drops support for JRuby because JRuby is a pain in the arse.

Builds should pass now and we can release this as 5.0.1 or something @tubbo.

We should definitely consider making a 6.0.0 version of all the redis-rails gems soon that would drop support for Rails < 4.2 and Ruby < 2.2. That'll make this mess a lot easier to clean up. After that we can focus on merging all the repos into one.

**Comment by connorshea** [comment]
@tubbo thanks for merging! Any chance we can get an update on RubyGems now? :)

**Comment by tubbo** [comment]
@connorshea yeah, if you (or anyone else) could prove that this works in the real world I'll gladly release a new patch version.

**Comment by connorshea** [comment]
@tubbo this version conflict hell is, well, hell. I need redis-rack 1.6.0 on RubyGems as well.

**Comment by connorshea** [comment]
Regardless, currently running our test suite with GitLab. Will need redis-rack 1.6.0 and redis-actionpack 5.0.1, but it looks like the gems at least work with Rails 4.2.7. Unfortunately I don't have a Rails 5 app to test.

**Comment by tubbo** [comment]
great. i can test it on rails 5.

**Comment by connorshea** [comment]
Here's the commit (see Build tabs for Builds): https://gitlab.com/gitlab-org/gitlab-ce/commit/e8b836dccbd5a6bbda80657c7627b1071c706aae

It'll probably take another 30+ minutes for tests to all run.

**Comment by connorshea** [comment]
@tubbo okay, it looks like everything is passing

**Comment by tubbo** [comment]
@connorshea 5.0.1 is out on RubyGems, let me know how it works for you. :)

**Comment by connorshea** [comment]
@tubbo I also need redis-rack 1.6.0 on RubyGems if possible

**Comment by tubbo** [comment]
it should already be there https://rubygems.org/gems/redis-rack/versions/1.6.0

**Comment by connorshea** [comment]
@tubbo got merged into master of GitLab: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/7291

Thanks so much for helping with this ❤️

**Pull request merged**
