### PR TITLE
Fix version constraints and broken tests

### PR DESCRIPTION
**Pull request by tubbo**
Got rid of minitest-spec-rails which was causing the dependency hell on
this project, and converted all the minitest-spec syntax into regular
old xunit-style syntax for both ease-of-use and to reduce dependencies.
Additionally, removed a "version test" that is totally useless. Should
resolve our testing and versioning issues.

Shoutout to @connorshea for the help on this!

### CODE REVIEW

**Comment by connorshea** [comment]
This is awesome, thank you! ❤️

**Comment by connorshea** [comment]
Maybe this library should be developed all in one repository like rails itself is? That would resolve the dependency hell of having to rely on gems that aren't actually released and you could just have Travis build them all at once.

Either that or point the Gemfiles you use for testing to the git endpoints rather than using versions from RubyGems. Currently this makes it really painful to update any of the gems' tests.

**Comment by tubbo** [comment]
I think this project used to be developed all in one repo, and indeed it was a single gem, but various parts were refactored out so people could still use Redis stores without developers having to bank on Rails itself. For example, redis-rack does not require rails, and redis-activesupport only requires activesupport, not the entire rails framework. So in cases where rails' supporting gems are used without the framework itself, having each component be its own gem is definitely an advantage.

All that said, I think tracking every redis-store gem in the same repo would be a _lot_ easier to manage. It's how most multi-gem projects work, and why should we be any different? In fact, I think it's counter-productive for maintainers because it's harder for us to see new changes, and it's harder for contributors because it's difficult to reason about where to contribute the code (or issue) that you need integrated.

**Comment by connorshea** [comment]
@tubbo another point for migrating back to one repo is that the redis-rails gem supports only 5.0 whereas redis-actionpack supports 4.0, 4.1, 4.2, and 5.0 see [redis-rails' `test` directory](https://github.com/redis-store/redis-rails/tree/master/test) where there's no gemfiles whereas in this repo we have a [`test/gemfiles` directory](https://github.com/redis-store/redis-actionpack/tree/master/test/gemfiles).

Things are becoming out-of-sync and this is making development a mess.

**Comment by connorshea** [comment]
Thank you a dozen times over for helping clean this up, and sorry I'm someone limited in my capacity being that I'm a Ruby novice.

I've asked in the GitLab Slack if anyone is interested in helping you out, hopefully someone volunteers :)

**Comment by connorshea** [comment]
For whatever reason minitest-rails requires different versions for different versions of Rails, which is... fun: https://github.com/blowmage/minitest-rails#configure

I'd say dropping anything other than Rails 4.2/5.0 and anything below Ruby 2.1 would be a reasonable move since 2.0.x is EOL and so is anything below Rails 4.2.

Then we can just use two gemfiles rather than the 5 we have now.

**Pull request closed without merging**
