### PR TITLE
Rails 5 support

### PR DESCRIPTION
**Pull request by marcroberts**

### CODE REVIEW

**Comment by saks** [comment]
+1

**Comment by marcroberts** [comment]
I've rebased my fork agains the updated master, and left ruby 1.9 in there still.

I'll add multiple test gem files to test rails 4 and 5 explicitly

**Comment by tubbo** [comment]
hey @marcroberts, looks pretty good but we have a failing build...could you resolve those test failures? https://travis-ci.org/redis-store/redis-actionpack/builds/101072902

**Comment by marcroberts** [comment]
I'm working on fixing the Rails 5 failure, these recent commits should fix most/all of the other failures/errors.

**Comment by marcroberts** [comment]
That should sort it out

**Comment by tubbo** [comment]
@marcroberts thank you so much! unfortunately, travis seems to be stopped up on the jruby and rubinius tests, so I restarted the build to make sure they all pass. I'm sure they will given all of the various MRI versions passed, though...

**Comment by marcroberts** [comment]
Looking at travis, the Rubinius test did actually pass, and the jruby test won't pass for rails5 as Rack 2.x requires a more recent version of Ruby so that will have to be excluded from the matrix

**Comment by tubbo** [comment]
laaaame, thanks for excluding that :) we'll figure out what to do about jruby's tests later as we still have some time before the rails 5 RCs start getting released. as soon as these checks pass I'll merge.

**Comment by tubbo** [comment]
@marcroberts what's up with the rubinius & rails 4.1/4.0 tests?

**Comment by ujh** [comment]
According to the [Travis documentation](https://docs.travis-ci.com/user/languages/ruby#Rubinius) `rbx-19mode` isn't supported anymore.

> Note that the syntax of rbx-19mode isn’t supported anymore.

I guess that's where the failures are coming from.

**Comment by tubbo** [comment]
Since everything else is passing I'll take responsibility for editing `.travis.yml` to disable rbx-19mode going forward.

**Comment by tubbo** [comment]
Thanks for being so patient @marcroberts, and thank you again for providing these necessary updates so we can make sure that the redis-store gems are ready for Rails 5.

**Pull request merged**
