### PR TITLE
Test with all supported Rails versions

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by radar** [comment]
Thanks! What about Rails 8?

**Comment by n-rodriguez** [comment]
> Thanks! What about Rails 8?

@radar I'd like to make tests pass on older Rails versions first

https://github.com/n-rodriguez/redis-actionpack/actions/runs/11735561173

**Comment by n-rodriguez** [comment]
> Thanks! What about Rails 8?

Done : https://github.com/n-rodriguez/redis-actionpack/actions/runs/11757532910

**Comment by n-rodriguez** [comment]
@tubbo this PR is good to merge. Thank you!

**Review by fz-ryanbigg — APPROVED** [review]

**Review by radar — APPROVED** [review]

**Comment by radar** [comment]
Thank you ❤️

**Pull request merged**
