### PR TITLE
support the same values for domain as rails' session stores usually do

### PR DESCRIPTION
**Pull request by mreinsch**
This pull request addresses https://github.com/redis-store/redis-actionpack/issues/1 and https://github.com/redis-store/redis-store/issues/218, https://github.com/redis-store/redis-store/issues/108

I also needed to change the tests based on test in rails, so the options for the session store could be changed per test.

### CODE REVIEW

**Comment by radar** [comment]
Looks good to me. Merged!

**Comment by nbouscal** [comment]
Can we get a version bump for this? It's not too big of a deal for me to point to master in my Gemfile, but it has been 7 months :-)

**Comment by radar** [comment]
Done.

**Comment by nbouscal** [comment]
Awesome, thanks!

**Pull request closed without merging**
